nf_core_version: 3.1.0
repository_type: pipeline
template:
  author: Nicola Calonaci, Elena Buscaroli, Katsiaryna Davydzenka, Giorgia Gandolfi,
    Virginia Gazziero, Brandon Hastings, Asad Sadr, Rodolfo Tolloi, Lucrezia Valeriani and Giulio Caravagna
  description: Analysis pipleine to model tumour clonal evolution from WGS data (driver
    annotation, quality control of copy number calls, subclonal and mutational signature
    deconvolution)
  force: false
  is_nfcore: true
  name: tumourevo
  org: nf-core
  outdir: .
  version: 1.0dev
lint:
  actions_awsfulltest: False
