# General project info
site_name: tumourevo
site_description: Documentation for the tumourevo pipeline.
site_author: Cancer Data Science laboratory
repo_url: https://github.com/caravagnalab/tumourevo.git

nav:
  - Contents: 'contents.md'
  - Usage: 'usage.md'
  - Output: 'output.md'

theme: readthedocs

