contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #tumourevo channel"
    url: https://nfcore.slack.com/channels/tumourevo
    about: Discussion about the nf-core/tumourevo pipeline
